---

- name: Tasks on a RHEL host
  include: main-rhel.yml
  when: ansible_distribution == 'RedHat'

- name: Tasks on a CentOS host
  include: main-centos.yml
  when: ansible_distribution == 'CentOS'

- name: Install Java
  action: "{{ ansible_pkg_mgr }} name={{ jboss_java_pkg_name }} state=latest"
  when: install_java == true
  tags:
  - common

- name: Install Unzip
  action: "{{ ansible_pkg_mgr }} name=unzip state=latest"
  tags:
  - common

# initscripts are for : v6.x or older
- name: Install initscripts
  action: "{{ ansible_pkg_mgr }} name=initscripts state=latest"
  tags:
  - common
  when: ansible_distribution_major_version is version_compare('7', '<')

- name: Install PIP
  action: "{{ ansible_pkg_mgr }} name=python-pip state=latest"
  tags:
  - common
  when: transfer_method == 'csp-to-host'

- name: Install Python Dependencies
  pip:
    name: "{{item}}"
    state: present
  with_items:
   - requests
   - lxml
  tags:
  - common
  when: transfer_method == 'csp-to-host'

- name: Remove EPEL Package
  action: "{{ ansible_pkg_mgr }} name='epel*' state=absent"
  tags:
  - common
  when: transfer_method == 'csp-to-host'
