---
  - name: Subscribe the host
    redhat_subscription:
      state: present
      username: "{{ rhn_username }}"
      password: "{{ rhn_password }}"
      auto_attach: yes
      pool_ids: "{{ rh_poolid }}"
    tags:
      - jboss_eap
    when: ansible_distribution == 'RedHat'

  - name: Install required dependencies
    yum:
      state: latest
      name: "{{ item }}"
    loop:
      - java
      - unzip
      - initscripts
      - pip
    when: install_depedencies == true
    tags:
      - common

  - name: Install EPEL for CentOS
    yum: 
      name: epel-release
      state: latest
    tags:
      - common
    when: transfer_method == 'csp-to-host' and ansible_distribution == 'CentOS'

  - name: Check Pool ID definition
    fail: msg="Extra variable rh_poolid has not been defined. Please add it before running this playbook"
    when: rh_poolid is not defined


  - name: Enable Optional Repo for RHEL
    rhsm_repository:
      name: "{{ item }}"
    loop:
      - rhel-7-server-optional-rpms
      - rhel-7-server-extras-rpms
    tags:
      - common
    when: transfer_method == 'csp-to-host' and ansible_distribution == 'RedHat'

  - name: Download EPEL for RHEL
    yum:
      name: "{{ epel_rpm }}"
      state: latest
    tags:
      - common
    when: transfer_method == 'csp-to-host' and ansible_distribution == 'RedHat'


  - name: Install Python Dependencies
    pip:
      name: "{{ item }}"
      state: present
    loop:
     - requests
     - lxml
    tags:
      - common
    when: transfer_method == 'csp-to-host'

  - name: Remove EPEL Package
    yum:
      name: epel*
      state: absent
    tags:
      - common
    when: transfer_method == 'csp-to-host'
