---

- name: Subscribe the host
  redhat_subscription:
    state: present
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
    autosubscribe: true
  tags:
  - common


- name: Check Pool ID definition
  fail: msg="Extra variable rh_poolid has not been defined. Please add it before running this playbook"
  when: rh_poolid is not defined

- name: Attach to pool
  command: subscription-manager attach --pool="{{ rh_poolid }}"
  ignore_errors: yes
  tags:
  - common
  when: rh_poolid is defined

- name: Enable Optional Repo for RHEL
  command: "subscription-manager repos --enable rhel-7-server-optional-rpms"
  tags:
  - common
  when: transfer_method == 'csp-to-host'

- name: Enable Extras Repo for RHEL
  command: "subscription-manager repos --enable rhel-7-server-extras-rpms"
  tags:
  - common
  when: transfer_method == 'csp-to-host'

- name: Download EPEL for RHEL
  get_url:
    url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    dest: "/tmp"
  tags:
  - common
  when: transfer_method == 'csp-to-host'

- name: Install EPEL for RHEL
  action: "{{ ansible_pkg_mgr }} name=/tmp/epel-release-latest-7.noarch.rpm state=present"
  tags:
  - common
  when: transfer_method == 'csp-to-host'

